### ISSUE TITLE
quotes appearing around for data with datatype as Long

### ISSUE THREAD

**Issue by twinkle-sachdeva** [scala/pickling#308]
Hi,

I am using scala-pickling_2.10-0.10.0.jar to do case class to jSON converstion.
It is converting Long values also to string.

For example, for the case class below:
case class TestClass( startTime: Long, path: String, flavour: String, flavourPass: Boolean)

 println(toJsonString(TestClass(1276819200,null,"A",true)))

It is printing: 

{
  "$type": "Main.TestClass",
  "numberOfArgs": "1276819200",
  "path": null,
  "flavour": "A",
  "flavourPass": true
}

Is this a known limitation? How to get around it?

**Comment by heathermiller** [comment]
Hi there, this is deliberate. In short, it's because numbers in Java and JavaScript are represented differently (64-bit integers in Java vs 64-bit floating point in JavaScript). This article on SO explains it a bit more: http://stackoverflow.com/questions/17320706/javascript-long-integer

You could write your own custom Long pickler if you'd like to overlook this.

**Comment by heathermiller** [comment]
(Closing, please reopen if you think this requires more discussion :) )
